name: Qlty

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qlty:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run Qlty
        uses: qltyio/qlty-action@main
        with:
          config-file: .qlty.yaml
