name: RuboCop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop --parallel -f progress -f html -o tmp/rubocop/report.html
    - uses: actions/upload-artifact@v2
      with:
        name: rubocop-report
        path: tmp/rubocop/report.html
  reviewdog:
    runs-on: ubuntu-latest
    steps:
    - uses: reviewdog/action-setup@v1
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Run rubocop & reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec rubocop --parallel | reviewdog -reporter=github-pr-review -f=rubocop
